[Icon Theme]
Name=Zoth-Hermetic
Comment=Hermetic Emerald, Obsidian Void & Cyber Alchemical Vector Icons for ZOTHOS
Inherits=Papirus-Dark,Papirus,Adwaita,hicolor
Directories=512x512/apps,256x256/apps,128x128/apps,96x96/apps,64x64/apps,48x48/apps,32x32/apps,24x24/apps,16x16/apps,scalable/apps

[512x512/apps]
Size=512
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[256x256/apps]
Size=256
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[128x128/apps]
Size=128
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[96x96/apps]
Size=96
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[64x64/apps]
Size=64
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[48x48/apps]
Size=48
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[32x32/apps]
Size=32
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[24x24/apps]
Size=24
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[16x16/apps]
Size=16
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[scalable/apps]
Size=128
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable
